### ISSUE TITLE
[BUG] Error with the Cron DownloadTldPrices.php

### ISSUE THREAD

**Issue by Jojo1542** [openprovider/Openprovider-WHMCS-domains#108]
**Describe the bug**
Bug that doesn't give to you the option to download the TLD prices.

**To Reproduce**
1. Exeucute Cron DownloadTdlPrices.php

**Expected behavior**
You will need to wait some seconds, and then, you will see this error:
`root@webpanel:/home/admin/web/whost.es/public_html/modules/registrars/openprovider/cron# php -d max_execution_time=0 DownloadTldPrices.php
[WHMCS Application] ERROR: TypeError: Argument 1 passed to WHMCS\Database\MysqlCompat::setLastStatement() must be an instance of PDOStatement or null, boolean given, called in /home/admin/web/whost.es/public_html/vendor/whmcs/whmcs-foundation/lib/Database/MysqlCompat.php on line 0 and defined in /home/admin/web/whost.es/public_html/vendor/whmcs/whmcs-foundation/lib/Database/MysqlCompat.php:0 Stack trace: #0 /home/admin/web/whost.es/public_html/vendor/whmcs/whmcs-foundation/lib/Database/MysqlCompat.php(0): WHMCS\Database\MysqlCompat->setLastStatement(false) #1 /home/admin/web/whost.es/public_html/includes/dbfunctions.php(0): WHMCS\Database\MysqlCompat->mysqlQuery('INSERT INTO tbl...', Object(PDO)) #2 /home/admin/web/whost.es/public_html/includes/dbfunctions.php(0): full_query('INSERT INTO tbl...', NULL) #3 /home/admin/web/whost.es/public_html/includes/functions.php(0): insert_query('tblmodulelog', Array) #4 /home/admin/web/whost.es/public_html/modules/registrars/openprovider/OpenProvider/API/API.php(198): logModuleCall('OpenProvider NL', 'searchExtension...', 'Array\n(\n    [po...', 'Array\n(\n    [cu...', '', Array) #5 /home/admin/web/whost.es/public_html/modules/registrars/openprovider/OpenProvider/API/API.php(127): OpenProvider\API\API->process(Object(OpenProvider\API\Request)) #6 /home/admin/web/whost.es/public_html/modules/registrars/openprovider/OpenProvider/API/API.php(271): OpenProvider\API\API->sendRequest('searchExtension...', Array) #7 /home/admin/web/whost.es/public_html/modules/registrars/openprovider/Controllers/System/DownloadTldPricesCronController.php(52): OpenProvider\API\API->getTldsAndPricing() #8 /home/admin/web/whost.es/public_html/modules/addons/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Instance.php(47): OpenProvider\WhmcsRegistrar\Controllers\System\DownloadTldPricesCronController->Download(NULL) #9 /home/admin/web/whost.es/public_html/modules/addons/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Launch.php(54): WeDevelopCoffee\wPower\Core\Instance->execute('Download', NULL) #10 /home/admin/web/whost.es/public_html/modules/registrars/openprovider/cron/DownloadTldPrices.php(14): WeDevelopCoffee\wPower\Core\Launch->output(NULL, 'DownloadTldPric...') #11 {main} {"exception":"[object] (TypeError(code: 0): Argument 1 passed to WHMCS\\Database\\MysqlCompat::setLastStatement() must be an instance of PDOStatement or null, boolean given, called in /home/admin/web/whost.es/public_html/vendor/whmcs/whmcs-foundation/lib/Database/MysqlCompat.php on line 0 at /home/admin/web/whost.es/public_html/vendor/whmcs/whmcs-foundation/lib/Database/MysqlCompat.php:0)"} []
TypeError: Argument 1 passed to WHMCS\Database\MysqlCompat::setLastStatement() must be an instance of PDOStatement or null, boolean given, called in /home/admin/web/whost.es/public_html/vendor/whmcs/whmcs-foundation/lib/Database/MysqlCompat.php on line 0 in /home/admin/web/whost.es/public_html/vendor/whmcs/whmcs-foundation/lib/Database/MysqlCompat.php:0

#0 /home/admin/web/whost.es/public_html/vendor/whmcs/whmcs-foundation/lib/Database/MysqlCompat.php(0): WHMCS\Database\MysqlCompat->setLastStatement(false)
#1 /home/admin/web/whost.es/public_html/includes/dbfunctions.php(0): WHMCS\Database\MysqlCompat->mysqlQuery('INSERT INTO tbl...', Object(PDO))
#2 /home/admin/web/whost.es/public_html/includes/dbfunctions.php(0): full_query('INSERT INTO tbl...', NULL)
#3 /home/admin/web/whost.es/public_html/includes/functions.php(0): insert_query('tblmodulelog', Array)
#4 /home/admin/web/whost.es/public_html/modules/registrars/openprovider/OpenProvider/API/API.php(198): logModuleCall('OpenProvider NL', 'searchExtension...', 'Array\n(\n    [po...', 'Array\n(\n    [cu...', '', Array)
#5 /home/admin/web/whost.es/public_html/modules/registrars/openprovider/OpenProvider/API/API.php(127): OpenProvider\API\API->process(Object(OpenProvider\API\Request))
#6 /home/admin/web/whost.es/public_html/modules/registrars/openprovider/OpenProvider/API/API.php(271): OpenProvider\API\API->sendRequest('searchExtension...', Array)
#7 /home/admin/web/whost.es/public_html/modules/registrars/openprovider/Controllers/System/DownloadTldPricesCronController.php(52): OpenProvider\API\API->getTldsAndPricing()
#8 /home/admin/web/whost.es/public_html/modules/addons/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Instance.php(47): OpenProvider\WhmcsRegistrar\Controllers\System\DownloadTldPricesCronController->Download(NULL)
#9 /home/admin/web/whost.es/public_html/modules/addons/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Launch.php(54): WeDevelopCoffee\wPower\Core\Instance->execute('Download', NULL)
#10 /home/admin/web/whost.es/public_html/modules/registrars/openprovider/cron/DownloadTldPrices.php(14): WeDevelopCoffee\wPower\Core\Launch->output(NULL, 'DownloadTldPric...')
#11 {main}root@webpanel:/home/admin/web/whost.es/public_html/modules/registrars/openprovider/cron# ^C`

**Server info:**
 - Distro: Ubuntu 18.04
 - PHP: 7.2
 - Web server: [e.g. httpd, nginx] NGINX

**Comment by wmetge** [comment]
Hi @Jojo1542, thanks for the feedback. What version of WHMCS are you using?

**Comment by Jojo1542** [comment]
WHMCS 8.0.4, with PLUS license

**Comment by wmetge** [comment]
Hi @Jojo1542 , the latest release of the module should solve your issue.
