### ISSUE TITLE
[FR] Add support for domain contact verification

### ISSUE THREAD

**Issue by coriaweb** [openprovider/Openprovider-WHMCS-domains#12]
Adapt module to new whmcs options 7.6.

I would like to see the module adapted to the new options.

https://docs.whmcs.com/Domain_Contact_Verification

**Comment by wmetge** [comment]
Hi @coriaweb, thanks for making us aware that you'd like this feature to be added to the module. We will investigate the possibility of supporting contact verification messaging by the module.

**Comment by theemstra** [comment]
Maybe it can be combined with the WHMCS email verification method?

**Comment by sapillai** [comment]
Hi @coriaweb,

I am closing this issue as support for contact verification was added in version [3.4.1](https://github.com/openprovider/Openprovider-WHMCS-domains/pull/115).
 
![image](https://github.com/openprovider/Openprovider-WHMCS-domains/assets/97894083/dc465166-5811-4bdc-aee6-9ab96786f430)
