### ISSUE TITLE
[BUG] Premium domains transfer price

### ISSUE THREAD

**Issue by ykaramian** [openprovider/Openprovider-WHMCS-domains#171]
**Describe the bug**
When premium domains are enabled, this works nicely for registering domains, with correctly settled prices. However, when it comes to transferring a premium domain, the price via WHMCS is significantly lower than via OpenProvider itself. Most likely this is because the domain in question is not considered a premium domain on transfer.

**Server info:**
 - Distro: Debian 10
 - PHP: 7.4
 - Web server: apache2

**Comment by wmetge** [comment]
hello @ykaramian could you please provide the details of the issue (e.g. which domain you were trying to transfer) to our support team so they can investigate the issue in more detail?

**Comment by ykaramian** [comment]
@wmetge, this issue is fixed by updating the module.
Thanks a lot!

**Comment by wmetge** [comment]
@ykaramian great to hear! thank you for the feedback
