### ISSUE TITLE
[FR] Disable namespinning/domainsuggestions

### ISSUE THREAD

**Issue by eMiz0rz** [openprovider/Openprovider-WHMCS-domains#175]
Is it possible to disable the namespinning/domainsuggestions using domainsearch in the shopping cart? Suggested domains are actually pretty crap and I would like to disable this feature entirely. The domainsearch should only suggest other TLD's for the same domain, not other domains.

Maybe I just overlooked a setting, would like to know!

**Comment by wmetge** [comment]
@eMiz0rz if you would like to use the Openprovider domain lookup without providing namespinning, you can comment out this function:

https://github.com/openprovider/OP-WHMCS7/blob/19eee04d33cf541006f183d7c9940e52a960a0cb/modules/registrars/openprovider/openprovider.php#L291

**Comment by eMiz0rz** [comment]
Thanks! I tried but it disables the domainsuggestion functionality completely. I think my question wasn't entirely clear. When selecting different TLD's in WHMCS under Product/Services > Domain Pricing > Lookup Provider > Configure, it automatically not only searches for different TLD's but also different domains (SLD's). 

These suggestions are so bad, it only clogs up the interface without actually adding a better userexperience. For example, when you search for a domain like "gimmeanewdomain.com" you get results like "gimmeamoderndomain.com" or "gimmenodomain.com" etc.

The problem with this is even when you select 10 different TLD's to search for in the Lookup Provider configuration, maybe only 2 or 3 TLD's are actually being searched and all the other results are different SLD's. I'd like to stop search for other SLD's and only search for other (selected) TLD's. 

This is easily fixed by switching to the Standard WHOIS of WHMCS, but it takes up an hour to check if a domain is either free or not...

**Comment by sapillai** [comment]
Hi @eMiz0rz,

The domain suggestions are working as expected for me in newer versions of the module. 

![image](https://github.com/openprovider/Openprovider-WHMCS-domains/assets/97894083/fbd2869d-7067-483d-817d-f25a95cc294a)

Module log: 
![image](https://github.com/openprovider/Openprovider-WHMCS-domains/assets/97894083/c0a7c0d2-6e8f-4859-8f1e-31eb2ad7ee15)

![image](https://github.com/openprovider/Openprovider-WHMCS-domains/assets/97894083/f7f7f4f2-9a1a-4c35-9136-74ece7c4bacb)

Could you please test this also from your end with a recent version of the module? If you notice any issues, please reach out to our [support team](https://support.openprovider.eu/hc/en-us/articles/360001674667-Contact-Openprovider-Support) with WHMCS, Openprovider and PHP versions and module log ([enable module logging](https://docs.whmcs.com/Troubleshooting_Module_Problems) and reproduce the issue to get logs). 

With Openprovider addon installed and activated in your WHMCS, you should be able to download module and activity logs from **Addons >> Openprovider >>** click on the '**Download**' button.

![image](https://github.com/openprovider/Openprovider-WHMCS-domains/assets/97894083/969d06f3-0122-4047-b370-f1da597c314b)
