### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by e-ticino** [openprovider/Openprovider-WHMCS-domains#185]
**Describe the bug**
Tried to activate OpenProvider module on WHMCS 8.*

**Expected behavior**
Should connect to OP and validate credentials

**Screenshots**

**Server info:**
 - Distro:  CLOUDLINUX 7.9 v98.0.6 
 - PHP:  ea-php74
 - Web server: APACHE httpd

**Additional context**
Oops message:
Whoops\Exception\ErrorException: Declaration of Illuminate\Support\LazyCollection::sort(?callable $callback = NULL) must be compatible with Illuminate\Support\Enumerable::sort($callback = NULL) in /home/***/public_html/modules/registrars/openprovider/vendor/illuminate/support/LazyCollection.php:1024
Stack trace:
#0 /home/dominihost/public_html/vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError(64, 'Declaration of ...', '/home/***...', 1024)
#1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown()
#2 {main}

NB: disabled (renaiming) file LazyCollection.php and it apparently works...

**Comment by wmetge** [comment]
Thank you @e-ticino for bringing this to our attention, we'll look into it

**Comment by wmetge** [comment]
@e-ticino  it seems that there is an issue with the version of illuminate in our module and the one you are using. 

We've reworked our database version to not cause conflicts, we have it on [this branch](https://github.com/openprovider/Openprovider-WHMCS-domains/tree/fix-error-with-scopes)

would you be able to confirm that this solves your issue?

**Comment by maverick85** [comment]
I am having the same issue since I updated to this new version of the OpenProvider module.
Using AlmaLinux 8.4 and all the system software is up to date.

**Comment by maverick85** [comment]
I have updated to the version [this branch](https://github.com/openprovider/Openprovider-WHMCS-domains/tree/fix-error-with-scopes).

However I also see this branch is "21 commits behind master".
