### ISSUE TITLE
[BUG] Cancelled Domain in activity mail

### ISSUE THREAD

**Issue by DAThosting** [openprovider/Openprovider-WHMCS-domains#187]
**Describe the bug**
Non active domains are listed in "OpenProvider Activity Mail" as "Domain does not exist in Openprovider!".

**To Reproduce**
Add Domain and set the status e.g. to cancelled.
The mail will include this as an error.

**Expected behavior**
Check domain status.

**Comment by solucionesuno** [comment]
Same problem here.

**Comment by wmetge** [comment]
@solucionesuno and @DAThosting thanks for bringing this to our attention. We will look into it

**Comment by lennarttd** [comment]
Please note that with version 5.4 of the module the Openprovider cron sync feature is deprecated.

**Comment by wmetge** [comment]
@lennarttd thank you for mentioning that this feature is deprecated.

@solucionesuno and @DAThosting, not withstanding that this feature is deprecated, a fix has been released
