### ISSUE TITLE
[BUG] - Registered Domains - Domain Information

### ISSUE THREAD

**Issue by maverick85** [openprovider/Openprovider-WHMCS-domains#198]
**Describe the bug**
---
Reference thread for issue 196 that was prematurely closed and filled with wrong information, including the suggestion that the mentioned operator for comparison wasn't GDPR compliant. That was absolutely disgusting.

[[BUG] - Registered Domains - Domain Information](https://github.com/openprovider/Openprovider-WHMCS-domains/issues/196)

**Comment by wmetge** [comment]
@maverick85 Let us know if you'd like to talk with the Openprovider product owner for domains. You might be able to come to an understanding about what data you need to see in the WHOIS reports. 

We make no comments or insinuations that other registrars may or may not be GDPR compliant, we can only confirm that our processes are meant to comply with both ICANN accreditation conditions and GDPR stipulations. 

Only issues in this repository which are related to the functioning of the Openprovider WHMCS domain provisioning module will be left open for consideration.

**Comment by maverick85** [comment]
Yes I would quite appreciate if you put us in contact with the OpenProvider product owner for domains then, thank you. Looking forward for your feedback.

**Comment by maverick85** [comment]
Still waiting, thank you.
@wmetge

**Comment by wmetge** [comment]
I've asked him to contact you at the nearest available time

**Comment by maverick85** [comment]
Hi @wmetge thank you for your feedback! I have been contacted and following up via email. Have a nice day ahead!
