### ISSUE TITLE
Registrar TLD Sync Issue

### ISSUE THREAD

**Issue by varunprakashnkl** [openprovider/Openprovider-WHMCS-domains#200]
When I try to sync the tld I am getting errors like this how can solve this issue.

![Screenshot_1](https://user-images.githubusercontent.com/48172544/141878711-7bb9a468-9daa-4ea1-ba98-ed969cf5d40a.png)

**Comment by sapillai** [comment]
Hi @varunprakashnkl 

Please ensure to run the script '**DownloadTldPrices.php**' either manually via command line or using a cron job as described here: https://github.com/openprovider/Openprovider-WHMCS-domains/blob/master/docs/TLD_Pricing_sync_Utility.md
