### ISSUE TITLE
[BUG] Base table or view not found: 1146 Table 'whmcs.mod_contactsAdditional' doesn't exist in

### ISSUE THREAD

**Issue by willdashwood** [openprovider/Openprovider-WHMCS-domains#212]
**Describe the bug**
When viewing the contacts page - index.php?rp=/account/contacts&contactid= - the error is thrown. Can confirm, that no table exists by this name in the database.

**To Reproduce**
1. Navigate to index.php?rp=/account/contacts&contactid= when logged in as a user
2. See error

**Expected behavior**
It should not through this error.

**Screenshots**
<img width="1510" alt="Xnip2022-01-04_13-42-32" src="https://user-images.githubusercontent.com/4964200/148067978-e39c68db-a5cc-4690-a7e9-694edae583fb.png">

**Server info:**
 - Distro: CentOS
 - PHP: 7.4
 - Web server: LiteSpeed

**Additional context**
I'm guessing someone forgot to create this table in the module install/init script. What should the schema be?

**Comment by dinusharath** [comment]
Hi @willdashwood,
thank you for your feedback we have fixed this issue with our latest relese(5.4.2). Please take the latest release.

**Comment by dinusharath** [comment]
> Still happening for me after this changes

hey @wailer did you clear your cache?
could you please mention the scenario you got this error

**Comment by wailer** [comment]
Hello @dinusharath , I cleaned browser and whmcs template cache and the problem started when we enabled 
`'idnumbermod' => true,` on advanced module configuration.
As soon as you try to create or edit an existing connect we get the "table not exists" error. Also to confirm, the table really doesn't exist on database.
`PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dev_clients_whmcs.mod_contactsAdditional' doesn't exist in /vendor/illuminate/database/Connection.php:331`
Thank you,

**Comment by dinusharath** [comment]
> Hello @dinusharath , I cleaned browser and whmcs template cache and the problem started when we enabled `'idnumbermod' => true,` on advanced module configuration. As soon as you try to create or edit an existing contact in customer area we get the "table not exists" error. Also to confirm, the table really doesn't exist on database. `PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dev_clients_whmcs.mod_contactsAdditional' doesn't exist in /vendor/illuminate/database/Connection.php:331` Thank you,

Hey @wailer thank you for you feedback and info. we have done some improvement here please take the latest relese(5.4.3 or higher) and try again. make sure you have cleared cache.

**Comment by wailer** [comment]
Thank you , now it's not throwing error.
