### ISSUE TITLE
Some premium domain prices not correct

### ISSUE THREAD

**Issue by willdashwood** [openprovider/Openprovider-WHMCS-domains#216]
We have premium domains enabled (both in WHMCS settings and in advanced-module-configurations.php). We're using v5.4.2 of the module. We just had an order for the registration of a premium domain but WHMCS massively undercharged them.

This isn't affecting all premium domain; some are changing the correct price and some are not. See screenshots below. Both are premium domains both the first one is not charging correctly.

<img width="859" alt="Xnip2022-01-12_16-58-51" src="https://user-images.githubusercontent.com/4964200/149194610-ffd9bcd0-a1f6-4ee1-b5f5-bc0685d06052.png">

<img width="862" alt="Xnip2022-01-12_16-59-16" src="https://user-images.githubusercontent.com/4964200/149194617-c4090316-ca2d-4792-92cc-a6bcfa36f524.png">

I don't think this is an API issue either because I just created a custom script to test the API myself and it's giving the correct results.

https://ukhost4u.com/billing/checkDomainPrice.php

The OpenProvider WHMCS module doesn't always appear to be using them correctly. Feel free to check our site directly:

https://www.ukhost4u.com/billing/cart.php?a=add&domain=register

Obviously this means we're out of pocket on the domain that has just been registered and I'm not wondering how many other domains we've sold at a loss! Your urgent attention on this issue would be appreciated.

**Comment by willdashwood** [comment]
OK so this seems to have sorted itself so was it an API issue? I'll raise a ticket with support to get a refund on the incorrect price that we were supplied and therefore charged our customer.

**Comment by wmetge** [comment]
@willdashwood Please correct me if I'm mistaken, but I think our support team discovered that the issue had to do with promotion versus premium pricing, and not related to behavior of the module itself.

**Comment by willdashwood** [comment]
That would be news to me. I've not had any resolution to the ticket. Besides, it can't be the API because my test script that I created gave the correct results and yet WHMCS did not. Can you chase it up? I think the ticket has been forgotten about and we're still out of pocket based on the incorrect price. Whether it's the API or the WHMCS module, end result to us is the same.

**Comment by wmetge** [comment]
I'm sorry to hear that this ticket has not been resolved. I've contacted the support team and asked them to prioritize the investigation.

**Comment by willdashwood** [comment]
I just wanted to follow up on this issue for others who might also be caught out. Turns out the issue was nothing to do with premium domains. It was because there was a promotional price available for registering .store domain names.

However, the promotional discount only applied if we registered the domain directly via cp.openprovider.eu, not WHMCS. And yet the discount price was given to me by the the OpenProvider API using searchExtensionRequest. I have a script which updates our WHMCS domain registration/renewal/transfer prices daily which uses searchExtensionRequest. So this is where the problem stemmed from.

I believe this matter is being raised further because I don't believe it's right that the API provides a price that you don't get is using the API (i.e. this WHMCS module) to register a domain.

searchExtensionRequest is not very well documented and I'm still waiting for what I regard as fairly critical improvements from 2019. However, I do believe there is a variable "withDiscounts" which perhaps will ignore any promotional prices. I'm only guessing as it's not mentioned here:

https://doc.openprovider.eu/API_Module_Extension_searchExtensionRequest

It's not ideal because I'm sure there are sometimes promotional that are available for domain registered via WHMCS/API but I'd rather avoid all promotional discounts just to make sure we're not exposed to undercharging customers, as happened here. To be honest, I'd rather OpenProvider just offered the same price regardless of how the domain is registered, especially as this was news to me, but I guess they can set whatever rules they like.

**Comment by sapillai** [comment]
Hi @willdashwood,

I'm closing this issue as it is not a WHMCS module bug. I see that your support tickets were answered and an internal case was raised to address the issue with discount prices returned by API. If you have any further questions, please reach out to our [support team](https://support.openprovider.eu/hc/en-us/articles/360001674667-Contact-Openprovider-Support).
