### ISSUE TITLE
[BUG] This domain already exists in Openprovider but NOT active

### ISSUE THREAD

**Issue by willdashwood** [openprovider/Openprovider-WHMCS-domains#221]
I thought this issue had been addressed a long time ago. I think it might have crept back in during the transition from v3 to v4/5.

If a domain name has expired, WHMCS fails to automatically renew the domain name and has to be renewed manually. It leaves an entry in the module queue and generates a todo list item.

To be clear, this isn't domains that have fallen into redemption, in fact it seems to renew those just fine. I'm talking about domains that are just a day or so past their expiry date. It's not all of them either. I would be happy to provide a list.

**Comment by willdashwood** [comment]
Still getting this issue after upgrading to the latest 5.6 release.

**Comment by sapillai** [comment]
Hi @willdashwood,

Thank you for reporting the problem. We are really sorry to hear that you are facing trouble with automatic domain renewals via WHMCS. I will reach out to you to get more details on this so that we can investigate the problem.

**Comment by willdashwood** [comment]
Thanks. Feel free to drop me an email. It's getting really annoying having to manually renew domains.

**Comment by pmjcreations** [comment]
Since upgrading to WHMCS 8.6.1, I noticed that when my Domain Synchronisation cron runs, I see "does not exist in Op" to all the available domains, even if the domains are active.

**Comment by sapillai** [comment]
Hi @pmjcreations,

Sorry to hear about the problem.

Please create it as a new issue as it is different from the case mentioned in this thread. Our team will review it.

**Comment by sapillai** [comment]
Hi @willdashwood,

I am glad to inform you that this has been fixed in the latest version of the module - [version 5.8.0](https://github.com/openprovider/Openprovider-WHMCS-domains/releases/tag/v5.8.0).
