### ISSUE TITLE
[BUG] (new) Nationality field for .com has default AFR - African

### ISSUE THREAD

**Issue by micheldeking** [openprovider/Openprovider-WHMCS-domains#223]
When I choose to edit an existing .com domain in the whmcs admin where the nationality field value is not available yet since this field is new then it defaults to the first one in the list and thats AFR - African. We now have several African clients because we did not notice it ;-)

What you would expect is no value at all and a warning that a value should be entered or it should default to the country code of the client.

**Comment by wmetge** [comment]
hello @micheldeking , thanks for bringing this to our attention. 

If you are talking about the IDN option for .com domains [this commit ](https://github.com/openprovider/Openprovider-WHMCS-domains/commit/182067cfe950acfef812f2d12e66dd09c60de927) should fix the issue by setting 'None' as the default choice.

If you are observing that some parameter of the contact other than the IDN value is being set to AFR, please let us know and we'll look at it in more detail.

**Comment by sapillai** [comment]
Hi @micheldeking,

I am closing this issue as Wyler added a fix for IDN value on Mar 5, 2022. If you are still facing the issue, please reach out to our [support team](https://support.openprovider.eu/hc/en-us/articles/360001674667-Contact-Openprovider-Support) with a screenshot of the problem, WHMCS, Openprovider and PHP version details.
