### ISSUE TITLE
[BUG] domain create does not use the default renewal value

### ISSUE THREAD

**Issue by micheldeking** [openprovider/Openprovider-WHMCS-domains#224]
**Describe the bug**
When a new domain is registered then the autorenew value is not set. We have as default in whmcs and openprovider that a domain should have auto-renew status but the status is always 'do not autorenew' in Openprovider.

I guess the openprovider cron fixes this but we do not use that, our own cron fixes it but it should be set correctly with the create domain statement I guess. This has been the case for at least more then a year since we use this module.

**Comment by wmetge** [comment]
Hi @micheldeking thanks for bringing this to our attention. We will update it in an upcoming release.

**Comment by sapillai** [comment]
Hi @micheldeking,

I'm glad to inform you that has been changed in the latest [release](https://github.com/openprovider/Openprovider-WHMCS-domains/releases/tag/v5.8.0). All new domain registration using the new module will have auto-renew value set to 'default'.
