### ISSUE TITLE
[FR] Add support for custom nameservers

### ISSUE THREAD

**Issue by wailer** [openprovider/Openprovider-WHMCS-domains#225]
It would be really nice if we could use our own NS servers , somehow. I have seen this was possible some time ago opening  a ticket, but this was just discontinued.

Currently, this is the one and only point which prevents us from moving all our domains to openprovider, and I am sure this would attract more customers.

Hope you think about it, so you can provide a solution to achieve this.

Thanks.

**Comment by wmetge** [comment]
Hi @wailer ,

Thanks for the feedback. We've passed it on to our DNS product team who are considering various options for expanding the Openprovider offering.

**Comment by maverick85** [comment]
There's another issue/FR for this exact same matter, @wailer 
https://github.com/openprovider/Openprovider-WHMCS-domains/issues/152

**Comment by wmetge** [comment]
closing issue since it's a feature request for Openprovider, and not a feature request for the module
