### ISSUE TITLE
[BUG] Unable to reset to default nameservers

### ISSUE THREAD

**Issue by Raboo** [openprovider/Openprovider-WHMCS-domains#230]
**Describe the bug**
Resetting to default nameservers doesn't work using both admin interface and client interface.

**To Reproduce**
Reset/change to default nameservers.

**Expected behavior**
It should update the domain to use the openprovider nameservers.

**Screenshots**
Admin interface
<img width="295" alt="bild" src="https://user-images.githubusercontent.com/1148206/162629973-f3986f5e-9047-4e74-a301-f515a02534e2.png">

Client interface
<img width="268" alt="bild" src="https://user-images.githubusercontent.com/1148206/162630009-022b360b-3e5e-493b-9b79-be7e3407b2bb.png">

**Server info:**
 - Distro: Ubuntu
 - PHP: v.7.2
 - Web server: [e.g. httpd, nginx] nginx + httpd
 - WHMCS: 8.4
 - Plugin: v5.6

**Comment by Raboo** [comment]
Some updates.
When I try to change nameservers using manual input. The request that the module sends is:

```json
{
  "id": 23622688,
  "nameServers": [
    {
      "name": "ns1.openprovider.nl",
      "ip": null
    },
    {
      "name": "ns2.openprovider.be",
      "ip": null
    },
    {
      "name": "ns3.openprovider.eu",
      "ip": null
    }
  ]
}
```

response:
```json
{
  "code": 500,
  "message": "[500] Server error: `PUT https:\/\/api.openprovider.eu\/v1beta\/domains\/23622688` resulted in a `500 Internal Server Error` response:\n{\"desc\":\"An unknown domain error has occurred; for more details, please refer to the registry message below\",\"code\":399, (truncated...)\n",
  "total": 0,
  "data": []
}
```

When I use the **change to default** / **reset to default** function.
It sends the following request:

```json
{
  "id": 23622688,
  "nameServers": [
    {
      "name": "ns1.oldns.se",
      "ip": null
    },
    {
      "name": "ns2.oldns.se",
      "ip": null
    },
    {
      "name": "ns3.oldns.se",
      "ip": null
    },
    {
      "name": "ns4.oldns.se",
      "ip": null
    }
  ]
}
```

response:
```json
{
  "code": 0,
  "message": "",
  "total": 0,
  "data": {
    "modelName": "domainUpdateDomainResponseData",
    "id": 23622688,
    "status": "ACT"
  }
}
```

**Comment by wmetge** [comment]
hi @Raboo , thanks for bringing this to our attention. The module is sending a correct request, but the update is being rejected by the registry. Please contact Openprovider support team directly to understand the cause of the rejection. Please include the domain name, your reseller ID, and the date of the rejected request.

This issue will be closed because it is not related to the functioning of the module.
