### ISSUE TITLE
[BUG] WHCMS change arabic domain to ( transfer away )

### ISSUE THREAD

**Issue by tacchinero** [openprovider/Openprovider-WHMCS-domains#234]
**Describe the bug**
We are using WHCMS system and notice any Arabic domain register from enom via WHCMS after one day it will change to ( transfer away ) we need help to understand as once we change it manually to be active , it will immediately changed to ( transfer away )

**Comment by sapillai** [comment]
Hi @tacchinero,

>We are using WHCMS system and notice any Arabic domain register from enom via WHCMS

We don't manage ENOM registrar module. Please reach out to ENOM Support or [WHMCS Support](https://www.whmcs.com/submit-a-ticket/) for assistance on this.
