### ISSUE TITLE
[BUG] OpenProvider 5+ versions

### ISSUE THREAD

**Issue by ykaramian** [openprovider/Openprovider-WHMCS-domains#237]
**Describe the bug**

Steps to reproduce the behaviour:
The update from version 4 to version 5 is not working for us.
When installing version 5.4-REST, the module works but when some other module is installed and trying to enable, the following errors appear:

```
TypeError: Argument 2 passed to Illuminate\Database\Schema\Grammars\MySqlGrammar::compileCreate() must be an instance of Illuminate\Support\Fluent, instance of Illuminate\Support6\Fluent given, called in /var/www/clients/client1/web14/web/whmcs/modules/registrars/openprovider/vendor/illuminate/database/Schema/Blueprint.php on line 123 and defined in /var/www/clients/client1/web14/web/whmcs/vendor/illuminate/database/Schema/Grammars/MySqlGrammar.php:57
Stack trace:
0 /var/www/clients/client1/web14/web/whmcs/modules/registrars/openprovider/vendor/illuminate/database/Schema/Blueprint.php(123): Illuminate\Database\Schema\Grammars\MySqlGrammar->compileCreate()
1 /var/www/clients/client1/web14/web/whmcs/modules/registrars/openprovider/vendor/illuminate/database/Schema/Blueprint.php(96): Illuminate\Database\Schema\Blueprint->toSql()
2 /var/www/clients/client1/web14/web/whmcs/vendor/illuminate/database/Schema/Builder.php(290): Illuminate\Database\Schema\Blueprint->build()
3 /var/www/clients/client1/web14/web/whmcs/vendor/illuminate/database/Schema/Builder.php(167): Illuminate\Database\Schema\Builder->build()
```
The registrar module "openprovider" includes some Laravel components that are already in WHMCS. Due to version mismatch, other modules cannot create tables in the database (libraries are loaded from openprovider module, but should be loaded from WHMCS). 

When we try to install the newest version, after enabling the registrar module, the whole site breaks with an "Oops" message.
**Server info:**
 - Distro: Debian 11
 - PHP: 7.4
 - Web server: Apache2
 - WHMCS: 8.5

**Comment by sapillai** [comment]
@ykaramian please try version [5.6.2](https://github.com/openprovider/Openprovider-WHMCS-domains/releases/tag/5.6.2), it was released with a fix for the Illuminate version issue.

**Comment by ykaramian** [comment]
> @ykaramian please try version [5.6.2](https://github.com/openprovider/Openprovider-WHMCS-domains/releases/tag/5.6.2), it was released with a fix for the Illuminate version issue.

Working perfectly. Thanks!
