### ISSUE TITLE
issue external to open provider

### ISSUE THREAD

**Issue by subedinfo** [openprovider/Openprovider-WHMCS-domains#242]
-

**Comment by subedinfo** [comment]
If anyone goes for the same error as us believing the `latest` version published is a working version, here's a link to the working version - even if with errors:

[Openprovider-WHMCS-domains-3.3](https://github.com/openprovider/Openprovider-WHMCS-domains/tree/v3.3)

For all matters, we are completely astonished with this situation. It's unbelievable.

**Comment by MrKoopie** [comment]
Please close this issue @subedinfo if it has been resolved.
