### ISSUE TITLE
[BUG] Domain suggestions Buy Now buttom missed ?

### ISSUE THREAD

**Issue by ProTechEx** [openprovider/Openprovider-WHMCS-domains#245]
Hi,

does the module doesn't offer after Name spinning the "Buy Now" Button like in the enom lookup provider module ?
https://prnt.sc/QlFk366CwKv2

**Comment by MrKoopie** [comment]
What are you exactly looking for? The module does provide suggestions with a add to cart.

<img width="866" alt="Screenshot 2022-10-25 at 06 40 39" src="https://user-images.githubusercontent.com/3456873/197684409-caef8c06-e789-400f-9835-d89e72bdc360.png">
