### ISSUE TITLE
[BUG] High number of identical "searchPromoMessageRequest" calls from the module

### ISSUE THREAD

**Issue by sapillai** [openprovider/Openprovider-WHMCS-domains#246]
**Describe the bug**
After the upgrade of WHMCS to 8.5.1, a couple of our resellers started noticing a high number of identical "searchPromoMessageRequest" calls from the module which resulted in an IP block.

**To Reproduce**
1. Go to 'WHMCS Admin area >> View/Search Clients'.
2. Click on 'Client ID'
3. Check System Module Debug Log (Configuration > System Logs > Module Log)

**Expected behavior**
Implement the _config_validate function to use the native functionality to efficiently check connectivity to their API

**Screenshots**
![image](https://user-images.githubusercontent.com/97894083/190325329-81f7deb4-04ce-4f5d-a451-b5c32f88ddde.png)

**Server info:**
- WHMCS version: 8.5.1
- Openprovider module version: 5.6

**Additional context**
Feedback from WHMCS support:

```
The Openprovider code indicates that their API command tests the module's connection to their API: https://github.com/openprovider/Openprovider-WHMCS-domains/blob/608dd1e9a06ed99c0d3e3fc33dae5c03acad8ad8/modules/registrars/openprovider/Controllers/System/ConfigController.php#L228

I observe that the module does not currently implement the _config_validate function to use the native functionality to efficiently check connectivity to their API. Given this it's entirely possible that if the Openprovider's developers implement this, they'll be able to remove their connection check above which looks to be coded to trigger each time the module is invoked, thereby improving the performance of their code:

https://developers.whmcs.com/domain-registrars/config-options/

One change was made to clientsummary.php to use the module display name in the "Registrar" column as defined by the Metadata function in the module if available: https://jira.whmcs.com/browse/CORE-17397

The OpenProvider module does not appear to implement this function, so the system falls-back to deducing the module name using the filename and the first letter is capitalised.
```

**Comment by MrKoopie** [comment]
Hi @sapillai, I have found a similar issue when browsing all domains. I have create a PR here with the fix: https://github.com/openprovider/Openprovider-WHMCS-domains/pull/247
