### ISSUE TITLE
[BUG] Add support php 8.1

### ISSUE THREAD

**Issue by chronosceptor** [openprovider/Openprovider-WHMCS-domains#248]
When I update to php 8.1 I get this error:
```
Whoops Exception ErrorException:
Array and string offset access syntax with curly braces is no longer supported in /public_html/modules/registrars/openprovider/classes/idna_convert.class.php:425
```

![php81](https://user-images.githubusercontent.com/3496002/200465304-53c3ff4e-eec9-40e2-ae90-19f95e064b1b.png)

**Server info:**
 - Distro: CentOS v7.9.2009 
 - PHP: 8.1
 - Web server: httpd

**Comment by maverick85** [comment]
+1 for this.

I understand why WHMCS delayed PHP8 support, due to IonCube. OP's module? Zero idea.

**Comment by ikke-zelf** [comment]
Same problem here. this prevents from updating to php 8.1

**Comment by ikke-zelf** [comment]
Updated the affected class file and created a pull request for it.
It works on my installation (whmcs8.6 with huh 8.1 now)

**Comment by ikke-zelf** [comment]
https://github.com/openprovider/Openprovider-WHMCS-domains/pull/249

**Comment by webthingz** [comment]
Replace curly braces in  idna_convert.class.php did it for me..

PHP Fatal error: Array and string offset access syntax with curly braces is no longer supported

**Comment by maverick85** [comment]
Almost one month later, zero feedback from OpenProvider.

**Comment by RoelReijn** [comment]
> #249

This should be merged as soon as possible since PHP7.4 reached end of life yesterday and will not receive further security updates.

**Comment by wmetge** [comment]
Thank you for your feedback, the changes have been merged.
