### ISSUE TITLE
[BUG] Error when opening domain registrars page.

### ISSUE THREAD

**Issue by andreass01** [openprovider/Openprovider-WHMCS-domains#250]
**Describe the bug**
When clicking on domain registrars in WHMCS I get "Oops!
Something went wrong and we couldn't process your request."

**To Reproduce**
1. Go to WHMCS admin area
2. Click on Domain registrars
3.  See error
4. 
**Expected behavior**
The registrars page should have shown up
**Screenshots**

**Server info:**
 - Distro: CloudLinux
 - PHP: 8.1
 - Web server: [litespeed]

**Comment by sapillai** [comment]
Hello @andreass01,

Could you please enable Display Errors in WHMCS and share the full error message? You can find instructions at:  https://help.whmcs.com/m/troubleshooting/l/678235-troubleshooting-a-blank-page-oops-error-message

**Comment by andreass01** [comment]
> Hello @andreass01,
> 
> Could you please enable Display Errors in WHMCS and share the full error message? You can find instructions at: https://help.whmcs.com/m/troubleshooting/l/678235-troubleshooting-a-blank-page-oops-error-message

This is the full message:

`Whoops\Exception\ErrorException: Array and string offset access syntax with curly braces is no longer supported in /home/admin/domains/kubes.se/public_html/order/modules/registrars/openprovider/classes/idna_convert.class.php:425
Stack trace:
#0 /home/admin/domains/kubes.se/public_html/order/vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError()
#1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown()
#2 {main}`

**Comment by sapillai** [comment]
Hello @andreass01 

Thank you for reporting the problem and sharing the full error message. We are reviewing a fix for the problem and hoping to release it soon.

**Comment by sapillai** [comment]
Hello @andreass01

This has been fixed with a [patch](https://github.com/openprovider/Openprovider-WHMCS-domains/commit/024ac1312099fd79eebb3200ecf0568d2df2d986)
