### ISSUE TITLE
WHMCS error getting truncated

### ISSUE THREAD

**Issue by jibrahim1990** [openprovider/Openprovider-WHMCS-domains#257]
**Describe the bug**

While trying to register, transfer or modify a domain, if there is an error/issue with the request - WHMCS returns error in truncated form

```
[500] Server error: `POST [https://api.openprovider.eu/v1beta/domains`](https://api.openprovider.eu/v1beta/domains%60)
resulted in a `500 Internal Server Error` response: {"desc":"An error has
occurred; for more details, please refer to the registry message below. For
more information pleas (truncated...)
```

For example full error for the above domain registration was:  

```
"An error has occurred; for more details, please refer to the registry message below. For more information please check https:\/\/support.openprovider.eu\/hc\/en-us\/articles\/7265441900946","data":"Incorrect contact's details: PD******
-IR, 2004, Cannot create contact due to sanctions restrictions affecting IR (Iran), and\/or 'kermanshah'"
```

But WHMCS domain registration page and module logs didn't show the full error message.

**To Reproduce**
Try to register a domain using with registrant/domain owner location Iran. Or try to transfer a domain with invalid auth code.

**Expected behavior**
Complete error message should show in the WHMCS/module logs

**Screenshots**
<img width="842" alt="image" src="https://user-images.githubusercontent.com/97894083/210498232-e0a4c395-ca16-435a-9508-732d1fde27f3.png">

![image](https://user-images.githubusercontent.com/97894083/210500855-a0d37999-f236-452b-8edc-a7faf8772c1f.png)

**Server info:**
 - Distro: WHMCS 8.4.1
 - PHP: 7.4
 - Web server: httpd

**Additional context**
The same operations via API is returning full error message.

**Comment by sapillai** [comment]
This has been fixed in the new beta version.
