### ISSUE TITLE
[BUG] TypeError accessing Domain Registrars

### ISSUE THREAD

**Issue by sjdean** [openprovider/Openprovider-WHMCS-domains#261]
Unable to access Domain Registrars section

TypeError: Return value of openprovider_registrar_launch_decorator() must be an instance of mixed, array returned in /var/www/html/whmcs/modules/registrars/openprovider/openprovider.php:354
Stack trace:
#0 /var/www/html/whmcs/modules/registrars/openprovider/openprovider.php(40): openprovider_registrar_launch_decorator()
#1 /var/www/html/whmcs/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): openprovider_getConfigArray()
#2 /var/www/html/whmcs/vendor/whmcs/whmcs-foundation/lib/Module/Registrar.php(0): WHMCS\Module\AbstractModule->call()
#3 /var/www/html/whmcs/admin/configregistrars.php(0): WHMCS\Module\Registrar->call()
#4 {main}

**To Reproduce**
Go to Domain Registrars

**Expected behavior**

**Screenshots**

**Server info:**
 - Distro: Ubuntu 22.04
 - PHP: 7.4.30
 - Web server: Apache

**Comment by sapillai** [comment]
Hi @sjdean

Thank you for reporting the problem.

The issue has been identified and our development team will review and fix it as soon as possible. In the meantime, you can use [this module version](https://github.com/openprovider/Openprovider-WHMCS-domains/tree/ddad50f73bed3a6936672bf978a38dc92783032f) to resolve the issue.
