### ISSUE TITLE
Private/Child nameserver list show on whmcs.

### ISSUE THREAD

**Issue by dewdropz** [openprovider/Openprovider-WHMCS-domains#263]
Hello,

After a few days of creating the private/child nameserver, if I forget what name I created the private/child nameserver and if I want to change the IP, then that option cannot be done from whmcs client panel from this module. I want to see the nameserver list and change the IP later.

**Comment by sapillai** [comment]
Hi @dewdropz,

Thanks for submitting the feature request.

As our API allows users to get the details of private nameservers, we considered adding this feature to the module. WHMCS, however, does not provide the functionality to get/list child nameservers yet. You can see from the function index of the module development docs[ here](https://developers.whmcs.com/domain-registrars/function-index/) that there is no function to retrieve private/child nameserver information.

There is a feature request for this feature on WHMCS and you may vote for it - https://requests.whmcs.com/idea/display-registered-private-name-servers-display-registered-name-servers
