### ISSUE TITLE
When I downloaded 

### ISSUE THREAD

**Issue by hostelad** [openprovider/Openprovider-WHMCS-domains#266]
When I downloaded the plugin my site no longer works

**Comment by sapillai** [comment]
@hostelad 

Please share the following details so that we can help you to resolve the issue.

1. Steps to reproduce the problem
2. Full error message
3. WHMCS version
4. PHP version
5. Openprovider module version

I am looking forward to hearing back from you.

**Comment by hostelad** [comment]
![٢٠٢٣٠٣٠٧_١٢٥٠٠٥](https://user-images.githubusercontent.com/116871579/223387142-00332ce5-750f-48d6-be4b-8699cae307e4.png)

Whmcs 8.6.1
Php 7.4
Openprovider module version 5.6.4

**Comment by sapillai** [comment]
@hostelad 

Thank you for sharing version details.

Are you getting error/having problem when logging into WHMCS admin dashboard? Please share the exact steps to recreate the problem and a screenshot of the error/problem. If you are getting a blank page/oops error message, please enable display errors as described in https://help.whmcs.com/m/troubleshooting/l/678235-troubleshooting-a-blank-page-oops-error-message

**Comment by hostelad** [comment]
The problem is from your add-on. When you uploaded the add-on, the problem occurred

**Comment by sapillai** [comment]
Hi @hostelad,

We tested the module (version 5.6.4) and add-on with PHP 7.4 and WHMCS 8.6.1, but we couldn't find any issues in WHMCS installation. Without being able to recreate the issue and without knowing exact steps and details about the problem, it will be difficult for us to provide help.

> When I downloaded the plugin my site no longer works

You mentioned this at the start of the thread, but it is still not clear for us whether you are getting an error or a blank page. So I request you to provide details of the issue you are having and also please share exact steps to reproduce the problem on our end. 

If you prefer not to share the details publicly here, you can reach out to us [here](https://www.openprovider.com/company/contact-us/contact-support).
