### ISSUE TITLE
[BUG] Accounts created with a default (wrong) tag

### ISSUE THREAD

**Issue by lucasRolff** [openprovider/Openprovider-WHMCS-domains#279]
**Describe the bug**
Using the latest version of the OpenProvider registration module, whenever a new account is registered in WHMCS, it seems to auto-assign a tag on the OpenProvider side to the tag that was first created on my account.

On WHMCS it says `Tag: no tags`, however, when opening the customer in the OpenProvider control panel, it shows a tag assigned by default, this tag happens to be the first created tag of the current available tags in my OpenProvider account.

This is unfortunate, since the first tag created isn't the correct one (uses a different name).
Despite having then created yet another tag in OpenProvider and set that tags "translation" to "default", it's still the first one being selected.

In the screenshot below, the tag all accounts are assigned is the top one.
![https://snaps.hcdn.dk/IeLrtdq3KaRfs8IvfpcYtOuvQHbiUQ5KtF5Qy9L2xErSj.png](https://snaps.hcdn.dk/IeLrtdq3KaRfs8IvfpcYtOuvQHbiUQ5KtF5Qy9L2xErSj.png)

- `createcustomerrequest` sends: `"tags":[{"key":"customer","value":""}]`
- `retrievecustomerrequest` returns: `"tags":[{"modelName":"customerTags","key":"customer","value":"geXXXX"}]`

**To Reproduce**
1. Create tag `customer1` in OpenProvider panel
2. Create tag `customer2` in OpenProvider panel
3. Assign language `English (World)` to both accounts and define a "From" in each template.
4. Set the "Default" on customer2 tag.
5. In WHMCS, create a new account and buy a domain, where no tags are assigned to the account
6. You'll see `customer1` gets assigned to the handle in OpenProvider.

**Expected behavior**
No tag should be set automatically, if it should, allow me to set it.

**Screenshots**
Openprovider settings:
![https://snaps.hcdn.dk/IeLrtdq3KaRfs8IvfpcYtOuvQHbiUQ5KtF5Qy9L2xErSj.png](https://snaps.hcdn.dk/IeLrtdq3KaRfs8IvfpcYtOuvQHbiUQ5KtF5Qy9L2xErSj.png)

WHMCS Account:
![https://snaps.hcdn.dk/2RZqKdgqxO8H7DwTKZ5LbZJO92wHsW5GPpGAg2LVLfSqO.png](https://snaps.hcdn.dk/2RZqKdgqxO8H7DwTKZ5LbZJO92wHsW5GPpGAg2LVLfSqO.png)

OpenProvider handle overview:
![https://snaps.hcdn.dk/6p6SVE4iqwpbj3a36BMcnTJy1e6XanHFShSRXrEN98C0M.png](https://snaps.hcdn.dk/6p6SVE4iqwpbj3a36BMcnTJy1e6XanHFShSRXrEN98C0M.png)

**Server info:**
 - Distro: Oracle Linux 9
 - PHP: 8.1
 - Web server: nginx

**Comment by sapillai** [comment]
Hi @lucasRolff,

Thank you for reporting the problem and sharing details. Our WHMCS team will investigate the case.

**Comment by sapillai** [comment]
Hi @lucasRolff,

I'm happy to inform you that this bug has been fixed on the API side.
