### ISSUE TITLE
[BUG] HTTP error when Update DNSSEC

### ISSUE THREAD

**Issue by payrequestio** [openprovider/Openprovider-WHMCS-domains#298]
**Describe the bug**
When I try to add a DNSSEC record

**To Reproduce**
1. Go to Domain
2. Click on  DNSSEC
3. Activate DNSSEC and insert value and click on Save
4. Nothing happens

**Expected behavior**
Add the DNSSEC records.

**Server info:**
 - PHP:   7.4
 - Web server:  Apache

**Error in console**
Mixed Content: The page at 'https://domain.shop/dnssec.php?domainid=447' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://domain.shop/modules/registrars/openprovider/api/dnssec-record-update/?flags=256&alg=3&pubKey=thekey&domainId=447&action=create'. This request has been blocked; the content must be served over HTTPS.

**Comment by sapillai** [comment]
Hi @payrequestio,

Sorry to hear that you have trouble adding DNSSEC record from WHMCS client area.

I tried to recreate the problem in my WHMCS environment, but I couldn't as the request for dnssec-record-update was sent over https. To assist you better, we'll need more details about the problem. Can you please share the following details to our [support team](https://www.openprovider.com/company/contact-us/contact-support)?
 
- Reseller ID and domain name
- WHMCS version and Openprovider module version
- Screen record with browser console logs

**Comment by sapillai** [comment]
Hi @payrequestio,

I'm closing this as we are unable to recreate the issue and haven't heard back from you in the support ticket. If the issue still persists, please reach out to our [support team](https://www.openprovider.com/company/contact-us/contact-support) with details.
