### ISSUE TITLE
WHMCS 8.8 support [BUG]

### ISSUE THREAD

**Issue by JEEBEE123** [openprovider/Openprovider-WHMCS-domains#304]
Hi,

I'm using WHMCS 8.8 but when I enable the Openprovider the back-end gets really slow.

When does this module become compatible with version 8.8?

**Comment by sapillai** [comment]
Hi @JEEBEE123,
 
A beta version of the new module with PHP 8.1 bug fixes and compatible with WHMCS 8.9 is available for testing. If you would like to participate in beta testing, please [contact our support team](https://support.openprovider.eu/hc/en-us/articles/360001674667-Contact-Openprovider-Support) or your account manager.
