### ISSUE TITLE
[BUG] Cannot disable balance widget

### ISSUE THREAD

**Issue by willdashwood** [openprovider/Openprovider-WHMCS-domains#311]
**Describe the bug**
Clicking the cross to close/remove the OpenProvider balance widgit on the administrator dashboard doesn't work. The widget adds a significant delay to the page load.

**To Reproduce**
1. Go to the administrator dashboard
2. Click on the cross to remove the OpenProvider balance widgit
3. Nothing happens

**Expected behavior**
The widgit should dissappear 

**Server info:**
 - Distro: CloudLinux 7 with cPanel
 - PHP: 8.1
 - Web server: LiteSpeed

**Additional context**
This was referenced in #253 . The only way to remove the widget at present is to delete files as follows.

`rm -f ./modules/registrars/openprovider/Controllers/Hooks/Widgets/BalanceWidget.php ./modules/registrars/openprovider/Controllers/Hooks/AdminWidgetController.php
`

**Comment by sapillai** [comment]
Hi @willdashwood,

Thank you for reporting the problem. I am able to reproduce the problem and we will check this.

**Comment by sapillai** [comment]
Hi @willdashwood,

I'm glad to inform you that the widget issue has been fixed in the latest [release](https://github.com/openprovider/Openprovider-WHMCS-domains/releases/tag/v5.8.0).

**Comment by junnurain** [comment]
How do I delete the widget in the admin dashboard? I deleted the open provider module. I want to fully delete the widget. Can you please assist me? 

https://prnt.sc/hSnrVDTp_D-4

**Comment by sapillai** [comment]
Hi @junnurain,

Widget files are located under the folder "**modules/registrars/openprovider/Controllers/Hooks**". If you are no longer using the Openprovider domain registrar module, you can remove the folders "**modules/registrars/openprovider**" &  "**modules/registrars/openprovider**" and this will remove the admin widget.
