### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by BenMeesters** [openprovider/Openprovider-WHMCS-domains#319]
We are using the Enable Openprovider Test mode

Describe the bug
After updating the module we proceeded to the Utility Registrar TLD Sync.
TLD Import & Pricing Sync: This reports a Cannot parse XML

To Reproduce

Go to Admin Panel
Click on Utilities
Scroll down to Registrar TLD Sync
See error
Expected behavior
A selection box should be displayed to select the OpenProvider option

Server info:

Distro: Debian bullseye
PHP: 8.1
Web server: Apache
Error:

connecting_with_openprovider_error
{"desc":"Method is not implemented","code":81}

**Comment by sapillai** [comment]
Hi @BenMeesters,

Really sorry for the delay in getting back to you. We recommend using our [support channels](https://www.openprovider.com/company/contact-us/contact-support) to get faster assistance.

The Sandbox environment has some limitation in fetching prices. An easy work-around will be to fetch TLD prices using your production API credentials in the WHMCS module and then switch back to Sandbox credentials.

- Configure the Openprovider module using live/production API credentials.
- Navigate to WHMCS Admin **Dashboard >> Utilities >> Registrar TLD Sync** >> Click on the Openprovider logo to fetch prices via API. The fetched prices will be stored in file: 'modules/registrars/openprovider/tld_cache.php'
- You can switch back to test mode with your Sandbox API credentials and prices will be loaded from 'tld_cache.php' file.
 
If you do not have a live account with us yet, please upload the copy of 'tld_cache.php' (download the zip file 'tld_cache.php.zip' from [here](http://openprovider-whmcs-lab-dev.nl/tld_cache.php.zip) and extract it) file to YOUR_WHMCS_PATH/modules/registrars/openprovider/. Once the file is uploaded to the folder, try running Registrar TLD Sync from the admin dashboard.
