### ISSUE TITLE
Upgrade from older version (howto) and configuration 2 question

### ISSUE THREAD

**Issue by DigiNL** [openprovider/Openprovider-WHMCS-domains#332]
Hello,

If i want to update from the current version to this latest build can i just overwrite the current files?

Does this latest version support PHP 7.x?

About the configuration, i want to go for version 2 but have a question:

```
Scenario 2. Not recommended by WHMCS

Openprovider Global Auto renew - On
WHMCS Auto Registration - On
WHMCS Automatic renewal - Off
The domain will be renewed at Openprovider on the expiration date, regardless of the invoice status (paid/unpaid).
When the end-user pays an invoice to renew a domain, the WHMCS next due date will increment one year.
No renewal commands are sent to Openprovider from WHMCS via the module.
Important: If a client doesn't pay the renewal invoice before expiry date, the domain's status in WHMCS will cycle from Active to Grace >> Redemption >> Expired, even though it was auto-renewed at Openprovider. To trigger the updating of the domain status and expiry date, the invoice would need to be paid in WHMCS, the renewal command successfully sent to your registrar and successfully processed.
```
Important: If a client doesn't pay the renewal invoice before expiry date, the domain's status in WHMCS will cycle from Active to Grace >> Redemption >> Expired, even though it was auto-renewed at Openprovider. To trigger the updating of the domain status and expiry date, the invoice would need to be **SET TO** paid **STATUS** in WHMCS, the renewal command successfully sent to your registrar and successfully processed.

****>> the renewal command successfully sent to your registrar and successfully processed** what does this mean? the domain has been renewed by open provider already, when reading this latest sentence it looks like the renew command is executed **- again -** is this right or is it only a sync for due dates and will the domain be set to active from the grace/redemption/expired status after this command is executed?**

The above (also set to paid status and the (second) renew command) are very important for me to know, please answer in understandable comment thanks.

**Comment by DigiNL** [comment]
Hello, can i get an answer

**Comment by sapillai** [comment]
Hi @DigiNL,

> If i want to update from the current version to this latest build can i just overwrite the current files?

If you haven't made any customizations to existing module files, you can overwrite the current files and folders with new version. 

- If you have made any customizations (for example, in file 'modules/registrars/openprovider/configuration/advanced-module-configurations.php'), please create a copy/backup of the customized files.
- Download the version of the module you need from https://github.com/openprovider/Openprovider-WHMCS-domains/releases. Extract it and upload contents as described in: https://support.openprovider.eu/hc/en-us/articles/360012991620-Install-and-configure-Openprovider-module-in-WHMCS-8-X
- Make sure the advanced config file 'modules/registrars/openprovider/configuration/advanced-module-configurations.php' has the right settings. If you have any custom settings in the current version, please ensure to copy/apply those to the new version. You can find detailed documentation about advanced module configuration at: https://github.com/openprovider/Openprovider-WHMCS-domains/blob/master/docs/advanced_configurations.md

> Does this latest version support PHP 7.x?

The latest version of the module has not been tested with PHP 7.x, as PHP 7.4 reached its End of Life in November 2022.

> the renewal command successfully sent to your registrar and successfully processed what does this mean? the domain has been renewed by open provider already, when reading this latest sentence it looks like the renew command is executed - again - is this right or is it only a sync for due dates and will the domain be set to active from the grace/redemption/expired status after this command is executed?

Scenario 2 is not recommended by WHMCS as domain renewals are handled outside WHMCS. 

According to WHMCS support, updating the status and expiry date of domains in WHMCS requires the renewal invoice to be paid, the renewal command sent to the registrar, and the command to be processed successfully. However, in scenario 2, where no renewal command is sent from WHMCS to the registrar, the domain status will not be updated if the domain has already passed expiration date in WHMCS. To transition a domain out of Grace or Expired status, the Renew module command must be completed in WHMCS.

With renewal settings as per scenario 2, when the end-user pays an invoice to renew a domain, the WHMCS next due date will increment one year. If they pay the invoice after the expiry date in WHMCS, domains will enter Grace or Expired status in WHMCS and will need to be updated (status and expiration date) manually as the native [WHMCS domain sync cron](https://developers.whmcs.com/domain-registrars/domain-syncing/) won't check and sync the status of domains with Grace or Expired status in WHMCS. When using scenario 2, there is a high chance for domains to end up in wrong statuses and expiry dates in WHMCS. For these reasons, it is recommended to use scenario 1. 

For technical questions, please reach out to [our Support team](https://www.openprovider.com/company/contact-us/contact-support) for quicker assistance.
