### ISSUE TITLE
[FR]Update for the upcomming version from WHMCS 8.11 that supports php 8.2

### ISSUE THREAD

**Issue by APOODesign** [openprovider/Openprovider-WHMCS-domains#334]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sapillai** [comment]
Hi @APOODesign,

Thank you for submitting the request.

We are already working on a new version of the Openprovider domain registrar module which will be compatible with WHMCS 8.11 and PHP 8.2. We are planning to release beta version of the new module by the end of this quarter.

**Comment by Gerbildral** [comment]
> Hi @APOODesign,
> 
> Thank you for submitting the request.
> 
> We are already working on a new version of the Openprovider domain registrar module which will be compatible with WHMCS 8.11 and PHP 8.2. We are planning to release beta version of the new module by the end of this quarter.

any idea which date it will be available?

**Comment by sapillai** [comment]
Hi @Gerbildral,

We are planning beta release of the new version of the Openprovider module in October after QA testing.
