### ISSUE TITLE
[Feature request] Support Additional Data fields update from WHMCS Admin area

### ISSUE THREAD

**Issue by soberoctober** [openprovider/Openprovider-WHMCS-domains#91]
Currently, additional data is only passed to Openprovider API when the domain is being registered or transferred. 
However, WHMCS admins can change the data from the backend but this will not trigger the update in the contact data/domain's additional data.

**Desired result**
when additional data fields are changed in admin area, the appropriate domain and contact should be updated as well

**Comment by sapillai** [comment]
As per WHMCS [documentation](https://docs.whmcs.com/clients/client-profile/domains-tab/), this is not supported.

![image](https://github.com/openprovider/Openprovider-WHMCS-domains/assets/97894083/c01c1294-7196-4853-8317-29f4fdaf5f61)
